// This file is generated by Astro DB
declare module 'astro:db' {
	export const User: import("@astrojs/db/runtime").Table<
		"User",
		{"id":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"id","collection":"User","primaryKey":true}},"email":{"type":"text","schema":{"unique":true,"deprecated":false,"name":"email","collection":"User","primaryKey":false,"optional":false}},"role":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"role","collection":"User","primaryKey":false,"optional":false}},"password":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"password","collection":"User","primaryKey":false,"optional":false}}}
	>;
}
