POST http://localhost:4321/api/product HTTP/1.1
content-type: application/json

{
    "id": "022a6a51-0270-4be0-bda6-0a8dbf04129d",
    "title": "Thunderbolt sneakers X",
    "description": "for fly for fly for fly for fly for fly for fly v vvfor flyvv for flyfor flyfor flyfor fly for flyfor flyfor fly",
    "categoryId": "76a1d615-1b55-4332-afe7-ec5c635ff7ea",
    "brandId":"16ff8130-0a40-4127-9e62-448b3e9a6b35",
    "genre":"female",
    "imagePreview":"https://auctions.c.yimg.jp/images.auctions.yahoo.co.jp/image/dr000/auc0407/users/c1fff615136a2fcf4b5e8fc23bc24acaf926e085/i-img1118x1200-16881753160owdym15.jpg"
}