GET http://localhost:4321/api HTTP/1.1

###

POST http://localhost:4321/api/signup HTTP/1.1
content-type: application/json

{
    "email": "pu@gmail.com",
    "password": "asdfghjk",
    "id": "d6656872-9f31-4d13-b04e-34da5a0af637",
    "role": "seller"
}

###
POST http://localhost:4321/api/signin HTTP/1.1
content-type: application/json

{
    "email": "pu@gmail.com",
    "password": "asdfghjk"
}

###
GET http://localhost:4321/api/protected HTTP/1.1
content-type: application/json

###
POST http://localhost:4321/api/signout HTTP/1.1
content-type: application/json