GET http://localhost:4321/api HTTP/1.1

# User
###

POST http://localhost:4321/api/signup HTTP/1.1
content-type: application/json

{
    "email": "pu@gmail.com",
    "password": "asdfghjk",
    "id": "d6656872-9f31-4d13-b04e-34da5a0af637",
    "role": "seller"
}

###
POST http://localhost:4321/api/signin HTTP/1.1
content-type: application/json

{
    "email": "pu@gmail.com",
    "password": "asdfghjk"
}

###
GET http://localhost:4321/api/protected HTTP/1.1
content-type: application/json

###
POST http://localhost:4321/api/signout HTTP/1.1
content-type: application/json


# Product
###
POST http://localhost:4321/api/product HTTP/1.1
content-type: application/json

{
    "id": "022a6a51-0270-4be0-bda6-0a8dbf04129d",
    "title": "Thunderbolt sneakers",
    "description": "for fly for fly for fly for fly for fly for fly v vvfor flyvv for flyfor flyfor flyfor fly for flyfor flyfor fly",
    "categoryId": "76a1d615-1b55-4332-afe7-ec5c635ff7ea",
    "brand":"haven",
    "genre":"female",
    "imagePreview":"https://auctions.c.yimg.jp/images.auctions.yahoo.co.jp/image/dr000/auc0407/users/c1fff615136a2fcf4b5e8fc23bc24acaf926e085/i-img1118x1200-16881753160owdym15.jpg"
}

###
GET http://localhost:4321/api/products HTTP/1.1
